name: Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'

      - name: Build and Test npm Package
        run: |
          npm install
          npm run build
          npm run test

      - name: Publish npm Package
        run: |
          npm version $RELEASE_VERSION --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
