name: Deploy Beta

on:
  release:
    types: [published]

jobs:
  deploy_beta:
    name: Deploy Beta
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease }}
    steps:
      - name: Check Branch Name Format
        run: |
          re=v[0-9]+.[0-9]+.[0-9]+-beta
          if ! [[ ${{ github.event.release.target_commitish }} =~ $re ]]; then
            echo 'Target branch does not match expected regex pattern for beta releases (v[0-9]+.[0-9]+.[0-9]+-beta)'
            echo '${{ github.event.release.target_commitish }}'
            echo 'Please update your branch name to match the expected regex pattern'
            exit 1
          fi

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Check Release Version Format
        run: |
          re=[0-9]+.[0-9]+.[0-9]+-beta
          if ! [[ $RELEASE_VERSION =~ $re ]]; then
            echo 'Tag does not match expected regex pattern for beta releases (v[0-9]+.[0-9]+.[0-9]+-beta)'
            echo $RELEASE_VERSION
            echo 'Please update your tag to match the expected regex pattern'
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'

      - name: Build and Test npm Package
        run: |
          npm install
          npm run build
          npm run test

      - name: Publish npm Package
        run: |
          npm version $RELEASE_VERSION --no-git-tag-version
          npm publish --access-public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
