name: Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Release Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'

    - name: Build and Test npm Package
      run: |
           npm install
           npm run build
           npm run test

    - name: Publish npm Package
      run: |
            npm version $RELEASE_VERSION --no-git-tag-version
            npm publish
